version: "3.8"

services: 
  app:
    container_name: animal-recuses
    image: animal-recuses:v1
    build:
      dockerfile: Dockerfile
      context: .
      # Only build development stage from dockerfile
      target: development
    volumes: 
      - .:/animal-recuces/rest-api
      - ./animal-recuces/rest-api/node_modules
    ports:
      - "${NODE_APP_PORT}:${NODE_APP_PORT}"
    env_file:
      - .env
    restart: unless-stopped
    depends_on: 
      - postgres
      - redis

  postgres:
    image: postgres:14-alpine
    volumes: 
      - postgres-data:/var/lib/postgresql/data
    ports: 
      - "${NODE_APP_DB_PORT}:${NODE_APP_DB_PORT}"
    restart: unless-stopped
    environment: 
      - POSTGRES_USER=${NODE_APP_DB_USERNAME}
      - POSTGRES_PASSWORD=${NODE_APP_DB_PASSWORD}
      - POSTGRES_DB=${NODE_APP_DB_DATABASE}

  redis:
    image: redis:6.2.5-alpine
    volumes:
      - .docker/data/redis:/data
    restart: unless-stopped
    user: "1000:1000"

volumes: 
  postgres-data:
    



